function out1 = linkRotQuat(t,in2,in3,in4,in5)
%linkRotQuat
%    OUT1 = linkRotQuat(T,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    14-Apr-2023 20:11:30

q1dev__dt_0_ = in2(1,:);
q1flex__dt_0_ = in2(2,:);
q1sup__dt_0_ = in2(3,:);
rf1IMU1x = in3(16,:);
rf1IMU1y = in3(17,:);
rf1IMU2x = in3(22,:);
rf1IMU1z = in3(18,:);
rf1IMU2y = in3(23,:);
rf1IMU2z = in3(24,:);
rf1Devx = in3(19,:);
rf1Devy = in3(20,:);
rf1Devz = in3(21,:);
t2 = q1dev__dt_0_./2.0;
t3 = q1flex__dt_0_./2.0;
t4 = q1sup__dt_0_./2.0;
t5 = rf1IMU1x./2.0;
t6 = rf1IMU1y./2.0;
t7 = rf1IMU2x./2.0;
t8 = rf1IMU1z./2.0;
t9 = rf1IMU2y./2.0;
t10 = rf1IMU2z./2.0;
t11 = rf1Devx./2.0;
t12 = rf1Devy./2.0;
t13 = rf1Devz./2.0;
t14 = cos(t2);
t15 = cos(t3);
t16 = cos(t4);
t17 = cos(t5);
t18 = cos(t6);
t19 = cos(t7);
t20 = cos(t8);
t21 = cos(t9);
t22 = cos(t10);
t23 = cos(t11);
t24 = cos(t12);
t25 = cos(t13);
t26 = sin(t2);
t27 = sin(t3);
t28 = sin(t4);
t29 = sin(t5);
t30 = sin(t6);
t31 = sin(t7);
t32 = sin(t8);
t33 = sin(t9);
t34 = sin(t10);
t35 = sin(t11);
t36 = sin(t12);
t37 = sin(t13);
out1 = reshape([1.0,0.0,0.0,0.0,t17.*t18.*t20+t29.*t30.*t32,t18.*t20.*t29-t17.*t30.*t32,t17.*t20.*t30+t18.*t29.*t32,t17.*t18.*t32-t20.*t29.*t30,t23.*t24.*t25+t35.*t36.*t37,t24.*t25.*t35-t23.*t36.*t37,t23.*t25.*t36+t24.*t35.*t37,t23.*t24.*t37-t25.*t35.*t36,t14.*t15.*t16+t26.*t27.*t28,t14.*t16.*t27-t15.*t26.*t28,t14.*t15.*t28+t16.*t26.*t27,t15.*t16.*t26-t14.*t27.*t28,1.0,0.0,0.0,0.0,t19.*t21.*t22+t31.*t33.*t34,t21.*t22.*t31-t19.*t33.*t34,t19.*t22.*t33+t21.*t31.*t34,t19.*t21.*t34-t22.*t31.*t33,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0],[4,11]);
