function [inertM,inertGF,inertCenMat,inertCorMatLeft,inertCorMatRight]=Inertial_TAWE(t,q,p,u,s,TF_Global,Vel_Global,Cor_Global,Jac_Global,Full_Flag_)
%% Author: Jiamin Wang; Updated: 2021-12-15;
    BaseFrameList=[6   7  21  22  23  24  25  26];
    MassList=Mass_TAWE(t,q,p,s,u);
    if Full_Flag_
        MomentList=reshape(Moment_TAWE(t,q,p,s,u),[3 3 numel(MassList)]);
    end
    
    inertCorMatLeft=zeros(numel(q)/2,6*numel(MassList));
    inertCorMatRight=zeros(6*numel(MassList),numel(q)/2);
    inertM=zeros(numel(q)/2,numel(q)/2,numel(MassList));
    inertGF=zeros(numel(q)/2,numel(MassList));
    inertCenMat=zeros(numel(q)/2,numel(q)/2,numel(MassList));
    for bodyNum=1:numel(MassList)
        if Full_Flag_
            rotor=TF_Global(1:3,1:3,BaseFrameList(bodyNum));
            m=MassList(bodyNum);
            I=rotor*MomentList(:,:,bodyNum)*rotor.';
            w=Vel_Global(4:6,BaseFrameList(bodyNum));
            a=Cor_Global(1:3,BaseFrameList(bodyNum));
            alpha=Cor_Global(4:6,BaseFrameList(bodyNum));
        end
        vJacobian=Jac_Global(1:3,:,BaseFrameList(bodyNum));
        wJacobian=Jac_Global(4:6,:,BaseFrameList(bodyNum));
        
        inertCorMatRight(6*bodyNum+(-5:0),:)=[vJacobian;wJacobian];
        if Full_Flag_
            % thisInertCorMatLeft=[m*vJacobian;I*wJacobian].';
            % thisInertCorMatRight=[vJacobian;wJacobian]; %Take the time derivative of this to calculate coriolis numerically
            inertCorMatLeft(:,6*bodyNum+(-5:0))=[m*vJacobian;I*wJacobian].';
            inertCenMat(:,:,bodyNum)=- wJacobian.'* skew3_InertDynamicsOnly_(I*w) * wJacobian; % On the same side of Mqddot
            % inertM(:,:,bodyNum)=thisInertCorMatLeft*thisInertCorMatRight;
            % inertGF(:,bodyNum)= - thisInertCorMatLeft*[a;alpha] - wJacobian.'* cross(w,I*w); % on the different side of Mqddot
            inertM(:,:,bodyNum)=vJacobian.'*m*vJacobian+wJacobian.'*I*wJacobian;
            inertGF(:,bodyNum)=- vJacobian.'*m*a - wJacobian.'*(I*alpha+cross(w,I*w)); % on the different side of Mqddot
        end
    end
    function output_=skew3_InertDynamicsOnly_(w_)
        output_=[0 -w_(3) w_(2) ; w_(3) 0 -w_(1) ; -w_(2) w_(1) 0 ];
    end

	function out1 = Mass_TAWE(t,in2,in3,in4,in5)
	%Mass_TAWE
	%    OUT1 = Mass_TAWE(T,IN2,IN3,IN4,IN5)
	%    This function was generated by the Symbolic Math Toolbox version 9.1.
	%    14-Apr-2023 16:21:05
	m12 = in3(112,:);
	m13 = in3(63,:);
	m22 = in3(70,:);
	m23 = in3(77,:);
	m24 = in3(84,:);
	m25 = in3(91,:);
	m26 = in3(98,:);
	m27 = in3(105,:);
	out1 = [m12,m13,m22,m23,m24,m25,m26,m27];
	end

	function out1 = Moment_TAWE(t,in2,in3,in4,in5)
	%Moment_TAWE
	%    OUT1 = Moment_TAWE(T,IN2,IN3,IN4,IN5)
	%    This function was generated by the Symbolic Math Toolbox version 9.1.
	%    14-Apr-2023 16:21:05
	i12xx = in3(113,:);
	i12xy = in3(114,:);
	i13xx = in3(64,:);
	i12xz = in3(115,:);
	i12yy = in3(116,:);
	i13xy = in3(65,:);
	i12yz = in3(117,:);
	i13xz = in3(66,:);
	i13yy = in3(67,:);
	i12zz = in3(118,:);
	i13yz = in3(68,:);
	i13zz = in3(69,:);
	i22xx = in3(71,:);
	i22xy = in3(72,:);
	i23xx = in3(78,:);
	i22xz = in3(73,:);
	i22yy = in3(74,:);
	i23xy = in3(79,:);
	i24xx = in3(85,:);
	i22yz = in3(75,:);
	i23xz = in3(80,:);
	i23yy = in3(81,:);
	i24xy = in3(86,:);
	i25xx = in3(92,:);
	i22zz = in3(76,:);
	i23yz = in3(82,:);
	i24xz = in3(87,:);
	i24yy = in3(88,:);
	i25xy = in3(93,:);
	i26xx = in3(99,:);
	i23zz = in3(83,:);
	i24yz = in3(89,:);
	i25xz = in3(94,:);
	i25yy = in3(95,:);
	i26xy = in3(100,:);
	i27xx = in3(106,:);
	i24zz = in3(90,:);
	i25yz = in3(96,:);
	i26xz = in3(101,:);
	i26yy = in3(102,:);
	i27xy = in3(107,:);
	i25zz = in3(97,:);
	i26yz = in3(103,:);
	i27xz = in3(108,:);
	i27yy = in3(109,:);
	i26zz = in3(104,:);
	i27yz = in3(110,:);
	i27zz = in3(111,:);
	out1 = reshape([i12xx,i12xy,i12xz,i12xy,i12yy,i12yz,i12xz,i12yz,i12zz,i13xx,i13xy,i13xz,i13xy,i13yy,i13yz,i13xz,i13yz,i13zz,i22xx,i22xy,i22xz,i22xy,i22yy,i22yz,i22xz,i22yz,i22zz,i23xx,i23xy,i23xz,i23xy,i23yy,i23yz,i23xz,i23yz,i23zz,i24xx,i24xy,i24xz,i24xy,i24yy,i24yz,i24xz,i24yz,i24zz,i25xx,i25xy,i25xz,i25xy,i25yy,i25yz,i25xz,i25yz,i25zz,i26xx,i26xy,i26xz,i26xy,i26yy,i26yz,i26xz,i26yz,i26zz,i27xx,i27xy,i27xz,i27xy,i27yy,i27yz,i27xz,i27yz,i27zz],[3,24]);
	end

end

